#!/bin/bash

SRV_USERNAME="nunocodex"

TG_BOT_LOG_CHAT="-1001182833534"
TG_BOT_MAINTAINERS_CHAT="-1001197980605"
TG_BOT_NEWS_CHAT="@CleanDroidOS"

CLEAN_BUILD_TYPE=OFFICIAL

REPO_MANIFEST_URL="https://github.com/CleanDroidOS/manifest"

ROOMSERVICE_DEFAULT_BRANCH="ten"
