version: 2
jobs:
  build:
    docker:
    - image: ubuntu:18.04

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/

    steps:
      - checkout

      - run:
          command: bash buildpe-notg.sh
