version: 2
jobs:
  build:
    docker:
    - image: ubuntu:18.04

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/android
    resource_class: xlarge
    steps:
      - checkout

      - run:
          command: free -h && apt update && apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev openjdk-11-jre openjdk-11-jdk liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev repo -y  && bash buildpe-notg.sh
