name: CI

on: 
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
     name: Building
     runs-on: ubuntu-18.04

  steps:
    - uses: repo-sync/github-sync@v2.0.0
    - name: GitHub Action for Bash
      uses: lafernando/github-action-bash@v1.0
      run: bash buildpe-notg.sh
